version: '3.8'

x-environment: &common-db-env
  MYSQL_DATABASE: hiddenviews
  MYSQL_USER: app
  MONGO_INITDB_DATABASE: hiddenviews
  MONGO_INITDB_ROOT_USERNAME: app

services:
  java:
    build: .
    volumes:
      - mediacache:/app/mediacache
    depends_on:
      - mongodb
      - mysqldb
    ports:
      - "8080:8080"
    networks:
      - app
    environment:
      <<: *common-db-env
    secrets:
      - secrets.meta.app-id
      - secrets.meta.client-secret
      - secrets.ig.user-id
      - secrets.ig.access-token.long-lived
      - secrets.mysql.password.default
      - secrets.mongo.password.root
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      <<: *common-db-env
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/secrets.mongo.password.root
    expose:
      - 27017
    networks:
      - app
    secrets:
      - secrets.mongo.password.root
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      <<: *common-db-env
      MYSQL_PASSWORD_FILE: /run/secrets/secrets.mysql.password.default
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secrets.mysql.password.root
    expose:
      - 3306
    networks:
      - app
    secrets:
      - secrets.mysql.password.default
      - secrets.mysql.password.root

volumes:
  mediacache:

networks:
  app:

secrets:
  secrets.meta.app-id:
    environment: HVM_META_APP_ID
  secrets.meta.client-secret:
    environment: HVM_META_CLIENT_SECRET
  secrets.ig.user-id:
    environment: HVM_IG_USER_ID
  secrets.ig.access-token.long-lived:
    environment: HVM_IG_LONG_LIVED_ACCESS_TOKEN
  secrets.mysql.password.default:
    environment: HVM_MYSQL_PASSWORD
  secrets.mysql.password.root:
    environment: HVM_MYSQL_ROOT_PASSWORD
  secrets.mongo.password.root:
    environment: HVM_MONGO_ROOT_PASSWORD